version: "3.8"

services:
  ip-resolve:
    build: .
    ports:
      - "7755:7755"
    environment:
      - NODE_ENV=production
      - PORT=7755
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:7755/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=ip-resolve"

  db-updater:
    build:
      context: .
      dockerfile: Dockerfile.cron
    restart: unless-stopped
    init: true
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yml:/app/docker-compose.yml:ro
    environment:
      - TZ=UTC
    depends_on:
      - ip-resolve
    labels:
      - "com.docker.compose.project=ip-resolve"
